### ISSUE TITLE
turtle not on $PATH. Need to set $JENA_HOME. Aborting.

### ISSUE THREAD

**Issue by jmatsushita** [AtomGraph/LinkedDataHub-Apps#1]
On a fresh install of LinkedDataHub, I tried to use the `./install.sh` for the skos demo in this repo.

Some instructions were missing in the getting started guide (which I understand focuses on setting up the SKOS demo manually, but does mention the alternative to install the demo app). I had to `chmod u+x` the `LinkedDataHub/scripts` repo as well as the `LinkedDataHub-Apps/demos/skos` scripts.

However, in the `### Creating containers` action, the install script failed with 
```
turtle not on $PATH. Need to set $JENA_HOME. Aborting.
```

It seems I could either install Jena on my client machine, or better, run the scripts from the docker instances. So I added these 2 volumes in the `docker-compose.yml` file:
```yaml
version: "2.3"
services:
  ...
  linkeddatahub:
    ...
    environment:
      ...
      - SCRIPT_ROOT=/scripts
    volumes:
      ...
      - ./scripts:/scripts
      - ../LinkedDataHub-Apps/demo:/scripts/demo
```

And then ran 
```
docker-compose up -d linkeddatahub # to reload the configuration
docker-compose exec linkeddatahub bash -c "(cd /scripts/demo/skos/ && ./install.sh https://localhost:4443/ /usr/local/tomcat/webapps/ROOT/certs/owner.p12.pem password)"
```

Final hurdle. `python` wasn't installed in the `linkeddatahub` container (which also means that installation depends on having python which I don't remember seeing in the requirements). So I mutated the container and it worked.

Another option to make all this user friendly without overloading the `linkeddatahub` container  would be to have a `console` container which is meant to mount the core and optionally demo scripts.

Hope this helps!
